export default [
  'An eccentric and wealthy collector hires the party to retrieve',
  'A pair of ethereal filchers are stealing all the curative magic in the',
  'A rather ugly troll armed with a club is tramping around a',
  'Feeling powerless against the local nobles, a town hires the PCs to kidnap',
  'Ships are disappering within a five-mile radius of',
  'A good and helpful aranea has been captured and tried for murder while the true culprit is',
  'A young child begins to manifest mage powers and is',
  'A couple forbidden to be together runs off to',
  'The heroes must protect a noble from',
  'A tinkerer is selling dangerous arcane artifacts to',
  'A Blood Mage cult is abducting people to use for',
  'Strange lights and sounds come from',
  'A dying miner claims to have found',
  'A friend of the heroes asks for help in',
  'A respected noble is accused of serious crimes; he destroyed',
  'An encounter with an ancient arcane item alters the heroes in some way until they can',
  'Two port towns dispute over the ownership of',
  'Two embattled Teyrns are planning secret raids on',
  'An ancient dwarven gate opens and',
  'The Dalish call for aid against',
  'Blight wolves and blight bears emerge from the wilderness to',
  'A young man begs the heroes to help stop a wedding because'
]